/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-122073-g7b773aba82-20251209"
#endif /* AVUTIL_FFVERSION_H */
